stack: kontena/kong
version: 0.2.0
description: Kong API gateway with PostgreSQL
expose: api
variables:
  bundle_postgres:
    type: boolean
    default: true
    from:
      env: BUNDLE_POSTGRES
      prompt: Use bundled postgres?
  postgres_host:
    skip_if:
      - bundle_postgres
    type: string
    default: postgres
    from:
      env: PG_HOST
      prompt: PostgreSQL Host
  postgres_user:
    skip_if:
      - bundle_postgres
    type: string
    default: kong
    from:
      env: PG_USER
      prompt: PostgreSQL User
  postgres_password:
    type: string
    from:
      vault: ${STACK}-postgres-password
      env: PG_PASSWORD
      prompt: Postgres password? (or empty to generate random)
      random_string: 32
    to:
      vault: ${STACK}-postgres-password
  postgres_db:
    skip_if:
      - bundle_postgres
    type: string
    default: kong
    from:
      env: PG_DATABASE
      prompt: PostgreSQL Database
  loadbalancer:
    type: string
    required: false
    from:
      env: LOADBALANCER
      service_link:
        prompt: Choose a loadbalancer
        image: kontena/lb
  virtual_hosts:
    only_if:
      - loadbalancer
    type: string
    from:
      env: VIRTUAL_HOSTS
      prompt: Domain names that point to your APIs (comma-separated list)
services:
  migrations:
    image: "kong:0.11-alpine"
    environment:
      - KONG_DATABASE=postgres
      # {% if bundle_postgres %}
      - KONG_PG_HOST=postgres.${STACK}.${GRID}.kontena.local
      - KONG_PG_DATABASE=kong
      - KONG_PG_USER=kong
      # {% else %}
      - KONG_PG_HOST=${postgres_host}
      - KONG_PG_USER=${postgres_user}
      - KONG_PG_DATABASE=${postgres_db}
      # {% endif %}
    secrets:
      - secret: ${STACK}-postgres-password
        name: KONG_PG_PASSWORD
        type: env
    command: sh -c "kong migrations up && tail -f /dev/null"
    # {% if bundle_postgres %}
    depends_on:
      - postgres
    # {% endif %}
  api:
    image: "kong:0.11-alpine"
    environment:
      - KONG_DATABASE=postgres
      # {% if bundle_postgres %}
      - KONG_PG_HOST=postgres.${STACK}.${GRID}.kontena.local
      - KONG_PG_DATABASE=kong
      - KONG_PG_USER=kong
      # {% else %}
      - KONG_PG_HOST=${postgres_host}
      - KONG_PG_USER=${postgres_user}
      - KONG_PG_DATABASE=${postgres_db}
      # {% endif %}
      # {% if loadbalancer %}
      - KONTENA_LB_INTERNAL_PORT=8000
      - KONTENA_LB_VIRTUAL_HOSTS=${virtual_hosts}
    links:
      - ${loadbalancer}
      # {% endif %}
    secrets:
      - secret: ${STACK}-postgres-password
        name: KONG_PG_PASSWORD
        type: env
    depends_on:
      - migrations
  # {% if bundle_postgres %}
      - postgres
  postgres:
    image: postgres:9.6-alpine
    stateful: true
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong
    secrets:
      - secret: ${STACK}-postgres-password
        name: POSTGRES_PASSWORD
        type: env
  # {% endif %}
